const initialState = {
  getNewsPending: false,
  getNewsError: null,
  loginPending: false,
  loginError: null,
  getCategoriesPending: false,
  getCategoriesError: null,
  getArticlesPending: false,
  getArticlesError: null,
  getPromotedPending: false,
  getPromotedError: null,
  registerPending: false,
  registerError: null,
  getUserPending: false,
  getUserError: null,
  postArticlePending: false,
  postArticleError: null,
  getArticlePending: false,
  getArticleError: null,
  fullUserPending: false,
  fullUserError: null,
  getSecArticlesPending: false,
  getSecArticlesError: null,
  getWriterPending: false,
  getWriterError: null,
  followUserPending: false,
  followUserError: null,
  userLikePending: false,
  userLikeError: null,
  reportArticlePending: false,
  reportArticleError: null,
};

export default initialState;
